import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
import { AppState } from 'store'
import { Status } from 'types'

export type Artist = {
  data: {
    id: number
    name: string
    link: string
    picture: string
    picture_small: string
    picture_medium: string
    picture_big: string
    picture_xl: string
    nb_album: number
    nb_fan: number
    radio: boolean
    tracklist: string
    type: 'artist'
  }[]
  total: number
  next: string
}

export type ArtistState = {
  status: Status
  data: Artist
  error: string | null | undefined
}

const initialState: ArtistState = {
  data: {} as Artist,
  status: Status.IDLE,
  error: null,
}

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(fetchArtists(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchArtists = createAsyncThunk(
  'artist/fetchArtists',
  async (artistQuery: string, { rejectWithValue }) => {
    try {
      // const response = await fetch(`https://api.deezer.com/search/artist/?q=eminem&output=json`)
      const response = await fetch(
        `/search/artist/?q=${artistQuery}&output=json`
      )
      const data = await response.json()

      if (!data || data?.errorMessage) {
        throw new Error('Data not found')
      }

      // The value we return becomes the `fulfilled` action payload
      return data
    } catch (error) {
      return rejectWithValue((error as Error).message)
    }
  }
)

export const artistSlice = createSlice({
  name: 'artist',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchArtists.pending, (state) => {
        state.status = Status.PENDING
        state.error = null
      })
      .addCase(fetchArtists.fulfilled, (state, action) => {
        state.status = Status.FULFILLED
        state.data = action.payload
        state.error = null
      })
      .addCase(fetchArtists.rejected, (state, action) => {
        state.status = Status.REJECTED
        state.data = {} as Artist
        state.error = action.payload as string
      })
  },
})

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: AppState) => state.artist.value)`
export const selectArtist = (state: AppState) => state.artists

export default artistSlice.reducer
