import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
import { AppState } from 'store'
import { Status } from 'types'

export type Track = {
  data: {
    id: number
    readable: boolean
    title: string
    title_short: string
    title_version: string
    isrc: string
    link: string
    duration: number
    track_position: number
    disk_number: number
    rank: number
    explicit_lyrics: boolean
    explicit_content_lyrics: number
    explicit_content_cover: number
    preview: string
    md5_image: string
    artist: {
      id: number
      name: string
      tracklist: string
      type: 'artist'
    }
    type: 'track'
  }[]
  total: number
}

export type TrackState = {
  status: Status
  data: Track
  error: string | null | undefined
}

const initialState: TrackState = {
  data: {} as Track,
  status: Status.IDLE,
  error: null,
}

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(fetchTracks(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchTracks = createAsyncThunk(
  'track/fetchTracks',
  async (trackQuery: string, { rejectWithValue }) => {
    try {
      // const response = await fetch(`https://api.deezer.com/search/track/?q=eminem&output=json`)
      const response = await fetch(`/album/${trackQuery}/tracks`)
      const data = await response.json()

      if (!data || data?.errorMessage) {
        throw new Error('Data not found')
      }

      // The value we return becomes the `fulfilled` action payload
      return data
    } catch (error) {
      return rejectWithValue((error as Error).message)
    }
  }
)

export const trackSlice = createSlice({
  name: 'track',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchTracks.pending, (state) => {
        state.status = Status.PENDING
        state.error = null
      })
      .addCase(fetchTracks.fulfilled, (state, action) => {
        state.status = Status.FULFILLED
        state.data = action.payload
        state.error = null
      })
      .addCase(fetchTracks.rejected, (state, action) => {
        state.status = Status.REJECTED
        state.data = {} as Track
        state.error = action.payload as string
      })
  },
})

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: AppState) => state.track.value)`
export const selectTrack = (state: AppState) => state.tracks

export default trackSlice.reducer
